<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <VersionPrefix>0.6.0</VersionPrefix>
        <Authors>Mike Morano &lt;mmorano@mikeandwan.us&gt;</Authors>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Humanizer" />
        <PackageReference Include="Humanizer.Core" />
        <PackageReference Include="NodaTime" />
        <PackageReference Include="NodaTime.Serialization.SystemTextJson" />
        <PackageReference Include="RestSharp" />
        <PackageReference Include="Spectre.Console" />
        <PackageReference Include="Spectre.Console.Cli" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ReverseGeocode.Tests" />
    </ItemGroup>

</Project>
